### ISSUE TITLE
OpenXR Platform Support

### ISSUE THREAD

**Issue by atx-barnes** [stytim/Mixed-Reality-Feature-Tool-For-Mac#1]
Is there support for OpenXR Platform download? I don't see it currently listed.

**Comment by stytim** [comment]
OpenXR was not included because there are Microsoft OpenXR, Meta OpenXR and Unity OpenXR. These OpenXR plugins can be imported via their own recommended ways.

**Comment by stytim** [comment]
OpenXR plugins: Microsoft Mixed Reality OpenXR and Unity Meta OpenXR are not includede in the tool
